const EXAMPLES = {
  "acknowledge": "The committee acknowledged his contribution to the project. / 委員会は彼のプロジェクトへの貢献を認めた。",
  "advocate": "She advocates for stricter environmental regulations. / 彼女はより厳しい環境規制を提唱している。",
  "alleviate": "The new policy aims to alleviate the burden on low-income families. / 新政策は低所得家庭の負担を軽減することを目指している。",
  "allocate": "The government allocated additional funds to public healthcare. / 政府は公衆衛生に追加資金を配分した。",
  "anticipate": "Economists anticipate a sharp decline in consumer spending. / 経済学者は消費支出の急激な落ち込みを予期している。",
  "articulate": "He articulated his concerns about the proposal clearly. / 彼は提案への懸念を明確に述べた。",
  "ascertain": "The investigators worked to ascertain the cause of the accident. / 調査員は事故の原因を突き止めようと努めた。",
  "assert": "The professor asserted that the experiment was fundamentally flawed. / 教授はその実験に根本的な欠陥があると主張した。",
  "assess": "The board will assess the risks before making a final decision. / 委員会は最終決定の前にリスクを評価する。",
  "assimilate": "Immigrants often struggle to assimilate into a new cultural environment. / 移民は新しい文化環境に同化するのに苦労することが多い。",
  "attain": "She attained a level of expertise few could match. / 彼女はほとんど誰も及ばない専門知識のレベルに到達した。",
  "augment": "The company augmented its workforce ahead of the busy season. / 会社は繁忙期に備えて労働力を増強した。",
  "collaborate": "The two universities collaborated to develop a groundbreaking vaccine. / 二つの大学が画期的なワクチン開発に協力した。",
  "compile": "The researcher compiled extensive data from multiple field studies. / 研究者は複数の現地調査から広範なデータをまとめた。",
  "comply": "All employees must comply with the updated safety regulations. / 全従業員は改訂された安全規制に従わなければならない。",
  "comprehend": "It is difficult to comprehend the full scale of the disaster. / 災害の全規模を理解することは難しい。",
  "contemplate": "She contemplated the ethical implications of the research. / 彼女はその研究の倫理的影響について熟考した。",
  "convey": "The documentary conveys a powerful message about climate change. / そのドキュメンタリーは気候変動について強力なメッセージを伝えている。",
  "cultivate": "Leaders must cultivate a culture of trust within their organizations. / リーダーは組織内に信頼の文化を育てなければならない。",
  "deduce": "From the evidence, the detective deduced that the crime was premeditated. / 証拠から、刑事は犯罪が計画的だったと推論した。",
  "deplete": "Overfishing has severely depleted the region's marine resources. / 乱獲により地域の海洋資源が深刻に枯渇した。",
  "derive": "Much of modern medicine derives its principles from ancient Greek practice. / 現代医学の多くはギリシャ古代の慣習から原則を導き出している。",
  "discern": "It is difficult to discern any meaningful pattern in the data. / データの中に意味のあるパターンを識別するのは難しい。",
  "elaborate": "The architect elaborated on the structural design of the new building. / 建築家は新しい建物の構造設計について詳しく説明した。",
  "evaluate": "Teachers must evaluate each student's progress objectively. / 教師は各生徒の進捗を客観的に評価しなければならない。",
  "facilitate": "Technology facilitates communication across international borders. / テクノロジーは国境を越えたコミュニケーションを促進する。",
  "formulate": "The team formulated a comprehensive strategy to address the crisis. / チームは危機に対処するための包括的戦略を立案した。",
  "implement": "The city council voted to implement stricter building codes. / 市議会はより厳しい建築基準を実施することを決議した。",
  "integrate": "The curriculum integrates scientific thinking with creative problem-solving. / カリキュラムは科学的思考と創造的問題解決を統合している。",
  "interpret": "Scholars interpret the ancient text in markedly different ways. / 学者たちはその古代テキストをまったく異なる方法で解釈する。",
  "justify": "He failed to justify the enormous costs of the program. / 彼はそのプログラムの膨大なコストを正当化できなかった。",
  "manipulate": "The politician was accused of manipulating public opinion through the media. / その政治家はメディアを通じて世論を操っていると非難された。",
  "monitor": "Health authorities monitor the spread of infectious diseases globally. / 保健機関は感染症の世界的な拡大を監視している。",
  "persist": "Despite repeated setbacks, the researchers persisted in their work. / 繰り返しの挫折にもかかわらず、研究者たちは研究を続けた。",
  "predict": "Analysts predict a significant shift in consumer behavior next year. / アナリストたちは来年の消費者行動に大きな変化を予測している。",
  "reinforce": "The findings reinforce the need for stricter emission controls. / その調査結果は排出規制強化の必要性を強化する。",
  "retain": "The company struggled to retain skilled employees in a competitive market. / 会社は競争激しい市場で熟練した従業員を維持するのに苦労した。",
  "stimulate": "Lower interest rates stimulate economic growth and investment. / 低金利は経済成長と投資を刺激する。",
  "sustain": "It is challenging to sustain momentum in the face of adversity. / 逆境の中で勢いを維持することは困難だ。",
  "transform": "Digital technology has transformed the way people access information. / デジタル技術は人々が情報にアクセスする方法を変容させた。",
  "undermine": "Constant criticism can undermine a person's confidence and motivation. / 絶え間ない批判は人の自信と意欲を損なう可能性がある。",
  "validate": "Further experiments are needed to validate these preliminary findings. / これらの予備的所見を検証するためにさらなる実験が必要だ。",
  "verify": "Journalists must verify sources before publishing sensitive information. / ジャーナリストは機密情報を公開する前に情報源を確認しなければならない。",
  "circumvent": "Some companies attempt to circumvent regulations through legal loopholes. / 一部の企業は法的抜け穴を通じて規制を回避しようとする。",
  "demonstrate": "The study demonstrates a clear link between stress and poor health. / その研究はストレスと不健康の明確な関連を実証している。",
  "designate": "The park was designated a UNESCO World Heritage Site in 2005. / その公園は2005年にユネスコ世界遺産に指定された。",
  "distinguish": "Experts can distinguish genuine antiques from skilled reproductions. / 専門家は本物の骨董品と巧みな複製品を区別できる。",
  "enhance": "Regular exercise can significantly enhance both physical and mental health. / 定期的な運動は身体的・精神的健康を著しく高める。",
  "generate": "Renewable energy sources generate electricity without harmful emissions. / 再生可能エネルギー源は有害な排出なしに電気を生成する。",
  "negotiate": "The two sides agreed to negotiate a peaceful resolution to the dispute. / 双方は紛争の平和的解決を交渉することに同意した。",
  "obtain": "Students must obtain a minimum score to qualify for the scholarship. / 奨学金の資格を得るには最低スコアを獲得しなければならない。",
  "overcome": "Through perseverance, she overcame the challenges of her early career. / 粘り強さを通じて、彼女はキャリア初期の困難を克服した。",
  "preserve": "It is vital to preserve endangered ecosystems for future generations. / 絶滅危惧の生態系を将来世代のために保存することが不可欠だ。",
  "promote": "The campaign promotes awareness of mental health issues among teenagers. / キャンペーンは十代の若者の精神的健康への意識を促進する。",
  "restrict": "The government restricted public gatherings during the health emergency. / 政府は健康上の緊急事態中に公的な集まりを制限した。",
  "revise": "The author revised the manuscript extensively before final submission. / 著者は最終提出前に原稿を徹底的に改訂した。",
  "specify": "The contract specifies the exact terms of the working arrangement. / 契約は勤務体制の正確な条件を明記している。",
  "speculate": "Analysts speculate that the merger will reshape the entire industry. / アナリストは合併が業界全体を再編成するだろうと推測している。",
  "substitute": "You can substitute olive oil for butter in most baking recipes. / ほとんどのベーキングレシピでバターをオリーブオイルで代替できる。",
  "utilize": "Modern surgeons utilize advanced robotics to improve precision. / 現代の外科医は精度を高めるために先進的なロボット技術を活用する。",
  "accumulate": "Wealth tends to accumulate among those who invest wisely over time. / 富は時間をかけて賢く投資する人々のところに蓄積される傾向がある。",
  "adhere": "All participants must adhere strictly to the study protocol. / 全参加者は研究プロトコルに厳格に従わなければならない。",
  "alienate": "Poor management decisions can alienate even the most loyal employees. / 経営上の悪い決断は最も忠実な従業員さえも疎外する可能性がある。",
  "compensate": "The firm compensated workers for overtime with additional paid leave. / 会社は残業に対して追加の有給休暇で従業員を補償した。",
  "emerge": "A new consensus is beginning to emerge from the ongoing negotiations. / 新たなコンセンサスが続く交渉から浮かび上がり始めている。",
  "ambiguity": "The ambiguity of the law left judges free to interpret it broadly. / 法律の曖昧さは裁判官に幅広く解釈する自由を与えた。",
  "analogy": "The teacher used an analogy to explain the concept of electric current. / 教師は電流の概念を説明するために類推を使った。",
  "anomaly": "Scientists detected an anomaly in the data that required further investigation. / 科学者たちはさらなる調査を要するデータの異常を検出した。",
  "assertion": "His assertion that the policy had failed was backed by solid evidence. / 政策が失敗したという彼の主張は確かな証拠に裏付けられていた。",
  "assessment": "A thorough assessment of the risks was conducted before the launch. / 発売前にリスクの徹底的な評価が実施された。",
  "assumption": "The entire argument rests on the assumption that demand will remain stable. / 議論全体は需要が安定したままだという前提の上に成り立っている。",
  "awareness": "Public awareness of climate change has grown significantly in recent years. / 気候変動への社会的認識はここ数年で著しく高まった。",
  "benchmark": "This performance serves as a benchmark for future evaluations. / この業績は将来の評価の基準として機能する。",
  "bias": "Researchers must guard against unconscious bias in their study designs. / 研究者は研究デザインの中の無意識の偏見を防がなければならない。",
  "catalyst": "The financial crisis served as a catalyst for sweeping regulatory reform. / 金融危機は大規模な規制改革の触媒として機能した。",
  "coherence": "The essay lacks coherence, making the argument difficult to follow. / その論文は一貫性に欠け、議論が理解しにくい。",
  "collaboration": "Successful collaboration between departments improved overall efficiency. / 部門間のうまい協力が全体の効率を改善した。",
  "competence": "The candidate demonstrated exceptional competence in handling complex negotiations. / 候補者は複雑な交渉に対処する卓越した能力を示した。",
  "complexity": "The complexity of the issue demands a nuanced and multi-faceted approach. / その問題の複雑さは微妙で多面的なアプローチを必要とする。",
  "component": "Trust is a critical component of any healthy professional relationship. / 信頼はあらゆる健全な職業的関係の重要な構成要素だ。",
  "constraint": "Budget constraints have limited the scope of the research program. / 予算の制約が研究プログラムの範囲を制限した。",
  "criterion": "The primary criterion for selection was academic excellence. / 選抜の主要な基準は学業上の優秀さであった。",
  "deficit": "The country faces a significant deficit in its national pension fund. / その国は国家年金基金に大きな不足を抱えている。",
  "dimension": "The social dimension of poverty is often overlooked in policy discussions. / 貧困の社会的側面は政策議論でしばしば見落とされる。",
  "discourse": "Academic discourse on this topic has evolved considerably over the decades. / このテーマについての学術的言説は数十年で大きく発展した。",
  "disparity": "The growing disparity in income distribution is a cause for concern. / 所得分配の拡大する格差は懸念の原因となっている。",
  "diversity": "The diversity of perspectives enriched the quality of the debate. / 視点の多様性が議論の質を豊かにした。",
  "endeavor": "Her lifelong endeavor to promote literacy changed thousands of lives. / 識字率を高めるための彼女の生涯にわたる努力は何千もの命を変えた。",
  "entity": "The corporation operates as a legally independent entity in each country. / その企業は各国で法的に独立した実体として運営されている。",
  "equilibrium": "The market will eventually reach a new equilibrium after the disruption. / 市場は混乱の後に最終的に新たな均衡に達するだろう。",
  "expertise": "Her expertise in molecular biology made her an invaluable asset to the team. / 分子生物学における彼女の専門知識はチームにとって非常に貴重な財産であった。",
  "framework": "The new framework provides clear guidelines for ethical decision-making. / 新しい枠組みは倫理的な意思決定のための明確な指針を提供している。",
  "hierarchy": "The strict hierarchy within the organization stifled creativity and innovation. / 組織内の厳格な階層は創造性と革新を抑制した。",
  "hypothesis": "The experiment was designed to test the researchers' central hypothesis. / その実験は研究者たちの中心的な仮説を検証するように設計された。",
  "implication": "The implications of this discovery extend far beyond the field of medicine. / この発見の含意は医学の分野をはるかに超えて広がっている。",
  "incentive": "Financial incentives alone are insufficient to motivate long-term commitment. / 金銭的な動機づけだけでは長期的なコミットメントを促進するのに不十分だ。",
  "inference": "The conclusion was based on inference rather than direct observation. / 結論は直接的な観察ではなく推論に基づいていた。",
  "innovation": "Continuous innovation is essential for maintaining competitive advantage. / 競争上の優位性を維持するには継続的な革新が不可欠だ。",
  "insight": "The study provided valuable insights into the causes of urban poverty. / その研究は都市の貧困の原因について貴重な洞察を提供した。",
  "integration": "Economic integration among member states has brought both benefits and challenges. / 加盟国間の経済統合は利益と課題の両方をもたらした。",
  "interpretation": "The historian's interpretation of the events challenged the traditional view. / 歴史家の出来事への解釈は従来の見方に異議を唱えた。",
  "investigation": "A formal investigation was launched to examine allegations of misconduct. / 不正行為の疑惑を調査するために正式な調査が開始された。",
  "justification": "There is no justification for the use of excessive force in this context. / この状況での過剰な力の使用に対する正当化はない。",
  "limitation": "The researchers acknowledged the limitations of their study methodology. / 研究者たちは研究方法論の限界を認めた。",
  "mechanism": "The mechanism by which the virus spreads is not yet fully understood. / ウイルスが広がる仕組みはまだ完全には理解されていない。",
  "methodology": "The methodology adopted in this study ensures reproducible results. / この研究で採用された方法論は再現性のある結果を保証する。",
  "momentum": "The reform movement gained momentum after the publication of the report. / 改革運動は報告書の発表後に勢いを増した。",
  "motivation": "Understanding the motivation behind consumer choices is key to marketing. / 消費者の選択の背後にある動機を理解することがマーケティングの鍵だ。",
  "narrative": "The official narrative failed to capture the full complexity of events. / 公式の物語は出来事の全複雑さを捉えるのに失敗した。",
  "obstacle": "Lack of funding remains the greatest obstacle to scientific progress. / 資金不足は科学的進歩への最大の障害であり続けている。",
  "outcome": "The outcome of the negotiations exceeded everyone's expectations. / 交渉の結果はすべての人の期待を超えた。",
  "paradox": "It is a paradox that greater connectivity can lead to increased isolation. / 接続性が高まると孤立が増すというのは逆説だ。",
  "phenomenon": "Social media addiction has become a widespread phenomenon among adolescents. / SNS依存は十代の若者の間で広く見られる現象となった。",
  "prerequisite": "A solid grasp of statistics is a prerequisite for this advanced course. / 統計学への確固たる理解がこの上級コースの前提条件だ。",
  "prevalence": "The prevalence of misinformation online poses a serious societal threat. / オンラインでの誤情報の広まりは深刻な社会的脅威をもたらしている。",
  "procedure": "All staff must follow the correct procedure when handling hazardous materials. / 全スタッフは有害物質を扱う際に正しい手順に従わなければならない。",
  "rationale": "The committee provided a clear rationale for its controversial decision. / 委員会は物議を醸す決定に対する明確な根拠を提示した。",
  "resilience": "Communities with strong social networks show greater resilience in crises. / 強固な社会的ネットワークを持つコミュニティは危機においてより高い回復力を示す。",
  "resolution": "The council reached a resolution on the disputed border after months of talks. / 評議会は数ヶ月の協議の末、係争中の国境について解決に達した。",
  "scrutiny": "Government spending should be subject to independent scrutiny. / 政府支出は独立した精査に服すべきだ。",
  "significance": "The historical significance of the discovery cannot be overstated. / その発見の歴史的な重要性はいくら強調してもし過ぎることはない。",
  "stability": "Political stability is a prerequisite for sustained economic development. / 政治的安定は持続的な経済発展の前提条件だ。",
  "stimulus": "The government introduced an economic stimulus to revive growth. / 政府は成長を回復させるために経済刺激策を導入した。",
  "transparency": "Greater transparency in government operations builds public trust. / 政府運営のより大きな透明性は公的信頼を築く。",
  "vulnerability": "Children living in poverty face heightened vulnerability to exploitation. / 貧困の中で育つ子どもたちは搾取に対する高い脆弱性に直面している。",
  "accountability": "The public demands greater accountability from elected officials. / 国民は選挙で選ばれた公務員からより大きな説明責任を求めている。",
  "adaptation": "The adaptation of species to changing climates is a slow process. / 変化する気候への種の適応は緩やかなプロセスだ。",
  "adherence": "Strict adherence to protocol is essential in clinical trials. / 臨床試験ではプロトコルへの厳格な遵守が不可欠だ。",
  "aftermath": "In the aftermath of the disaster, thousands were left without shelter. / 災害の余波の中で、何千人もが住居を失った。",
  "allegiance": "Citizens are expected to pledge allegiance to the constitution of the nation. / 市民は国家の憲法への忠誠を誓うことが期待される。",
  "apparatus": "The entire apparatus of the state was mobilized to manage the emergency. / 緊急事態に対処するために国家の全機構が動員された。",
  "commodity": "Water has increasingly become a scarce and valuable commodity worldwide. / 水は世界的に希少で価値ある商品になりつつある。",
  "concession": "The government made a significant concession to end the labor dispute. / 政府は労働争議を終わらせるために大きな譲歩をした。",
  "conviction": "She spoke with utter conviction that justice would ultimately prevail. / 彼女は正義が最終的に勝つという完全な確信を持って語った。",
  "correlation": "Research has established a strong correlation between education and income. / 研究は教育と収入の間の強い相関関係を確立した。",
  "deterrent": "Heavy fines serve as a powerful deterrent against corporate misconduct. / 重い罰金は企業不正行為に対する強力な抑止力として機能する。",
  "fluctuation": "Currency fluctuations can significantly affect the profitability of exports. / 通貨の変動は輸出の収益性に大きく影響する可能性がある。",
  "manifestation": "The protests were a clear manifestation of widespread public discontent. / その抗議活動は広範な公的不満の明確な現れであった。",
  "obligation": "Every citizen has an obligation to contribute to the welfare of society. / すべての市民には社会の福祉に貢献する義務がある。",
  "orientation": "The company provides a comprehensive orientation for all new employees. / 会社はすべての新入社員に包括的な方向付けを提供する。",
  "projection": "The latest economic projections indicate modest growth over the next decade. / 最新の経済予測は今後十年間のわずかな成長を示している。",
  "proposition": "The proposition that economic growth alleviates poverty remains debated. / 経済成長が貧困を軽減するという命題は依然として議論されている。",
  "regulation": "Stricter regulation of the financial sector was introduced after the crash. / 金融崩壊後、金融部門のより厳格な規制が導入された。",
  "scope": "The scope of the investigation was broadened to include related incidents. / 調査の範囲は関連事件を含むように拡大された。",
  "sequence": "The sequence of events leading to the crisis was carefully documented. / 危機に至る出来事の順序は慎重に記録された。",
  "submission": "The submission of the final report is due at the end of the month. / 最終報告書の提出は月末までが期限だ。",
  "tendency": "There is a tendency to underestimate the long-term consequences of inaction. / 行動を起こさないことの長期的な影響を過小評価する傾向がある。",
  "transition": "The country's transition to renewable energy has gained considerable pace. / 国の再生可能エネルギーへの移行はかなりの勢いを増した。",
  "trend": "The trend toward remote work is reshaping urban planning and infrastructure. / リモートワークへの傾向は都市計画とインフラを再構成している。",
  "uncertainty": "Economic uncertainty has made businesses reluctant to invest long-term. / 経済的不確実性が企業に長期投資を躊躇させている。",
  "reinforcement": "Positive reinforcement is more effective than punishment in behavioral training. / 行動訓練においては罰よりも正の強化の方が効果的だ。",
  "conundrum": "The ethical conundrum of balancing privacy and security remains unresolved. / プライバシーと安全保障のバランスという倫理的難問は未解決のままだ。",
  "complement": "Her technical expertise serves as a complement to his creative vision. / 彼女の技術的専門知識は彼の創造的ビジョンの補完として機能する。",
  "discrepancy": "There was a significant discrepancy between the projected and actual costs. / 予測コストと実際のコストの間に大きな食い違いがあった。",
  "endorsement": "The candidate received the endorsement of several influential organizations. / 候補者はいくつかの有力組織の支持を得た。",
  "premise": "The argument's validity depends entirely on the accuracy of its core premise. / 論証の妥当性はその中心的前提の正確さに全面的に依存する。",
  "priority": "Reducing carbon emissions must remain a national priority. / 炭素排出量の削減は国家の優先事項であり続けなければならない。",
  "prototype": "Engineers developed a working prototype of the new aircraft engine. / エンジニアは新しい航空機エンジンの動作するプロトタイプを開発した。",
  "spectrum": "The policy affects a broad spectrum of stakeholders across various sectors. / その政策はさまざまな分野にわたる広範なステークホルダーに影響する。",
  "standpoint": "From an environmental standpoint, the project raises serious concerns. / 環境の観点から見ると、そのプロジェクトは深刻な懸念を提起する。",
  "stereotype": "Challenging stereotypes is essential for building an inclusive society. / 固定観念に挑戦することは包括的な社会を築くために不可欠だ。",
  "threshold": "The noise levels exceeded the legal threshold set by local authorities. / 騒音レベルは地方当局が定めた法定閾値を超えた。",
  "notion": "The notion that success requires sacrifice is widely accepted. / 成功には犠牲が必要だという概念は広く受け入れられている。",
  "mandate": "The organization operates under a clear mandate to protect human rights. / その組織は人権を守るという明確な命令のもとで運営されている。",
  "repercussion": "The scandal had severe repercussions for the entire organization. / そのスキャンダルは組織全体に深刻な影響をもたらした。",
  "abstract": "The report presents highly abstract concepts that are difficult to quantify. / 報告書は定量化が難しい高度に抽象的な概念を提示している。",
  "ambiguous": "The wording of the contract was deliberately ambiguous to allow flexibility. / 契約の文言は柔軟性を持たせるために意図的に曖昧にされた。",
  "arbitrary": "The decision appeared arbitrary and lacked any clear justification. / その決定は恣意的に見え、明確な正当化を欠いていた。",
  "coherent": "She presented a coherent argument that convinced most of the committee. / 彼女は委員会のほとんどを納得させる一貫した論証を提示した。",
  "compelling": "The documentary presents a compelling case for immediate climate action. / そのドキュメンタリーは即時の気候行動への説得力のある主張を提示している。",
  "complex": "The relationship between poverty and crime is highly complex. / 貧困と犯罪の関係は非常に複雑だ。",
  "comprehensive": "A comprehensive review of the entire system is long overdue. / システム全体の包括的な見直しは長い間必要とされていた。",
  "controversial": "The proposed legislation proved highly controversial among opposition groups. / 提案された法律は反対派グループの間で非常に議論を呼ぶことが判明した。",
  "critical": "Critical thinking skills are essential in today's information-saturated world. / 批判的思考力は今日の情報が飽和した世界では不可欠だ。",
  "decisive": "The general took decisive action to prevent the conflict from escalating. / 将軍は紛争が拡大しないよう決定的な行動を取った。",
  "definitive": "This landmark study is regarded as the definitive work on the subject. / この画期的な研究はその主題に関する決定的な著作とみなされている。",
  "diverse": "The panel consisted of experts with diverse academic and professional backgrounds. / 委員会は多様な学術的・職業的背景を持つ専門家で構成されていた。",
  "dominant": "English has become the dominant language of global scientific communication. / 英語は世界的な科学的コミュニケーションの支配的な言語となった。",
  "dynamic": "The dynamic relationship between supply and demand shapes market prices. / 需要と供給の動的な関係が市場価格を形成する。",
  "explicit": "The contract contains explicit instructions regarding dispute resolution. / 契約は紛争解決に関する明示的な指示を含んでいる。",
  "extensive": "Extensive research was conducted before the drug received approval. / その薬が承認を受ける前に広範な研究が実施された。",
  "feasible": "The engineers concluded that the project was technically feasible. / エンジニアはそのプロジェクトが技術的に実行可能だと結論付けた。",
  "flexible": "A flexible approach is needed when dealing with unprecedented challenges. / 前例のない課題に対処する際には柔軟なアプローチが必要だ。",
  "fundamental": "Access to clean water is a fundamental human right. / 清潔な水へのアクセスは基本的人権だ。",
  "implicit": "The agreement contained implicit expectations that were never formalized. / その合意には正式化されることのない暗黙の期待が含まれていた。",
  "inevitable": "Given the circumstances, conflict seemed inevitable. / 状況を考えると、衝突は避けられないように思えた。",
  "inherent": "There are risks inherent in any form of financial investment. / あらゆる形態の金融投資には本来備わったリスクがある。",
  "integral": "Public engagement is integral to the success of democratic governance. / 市民の参加は民主的なガバナンスの成功に不可欠だ。",
  "intrinsic": "The intrinsic value of education extends far beyond career prospects. / 教育の本質的な価値はキャリアの見通しをはるかに超えて広がっている。",
  "legitimate": "The organization operates under a legitimate government mandate. / その組織は正当な政府の命令のもとで運営されている。",
  "objective": "The report aimed to present an objective analysis of the data. / 報告書はデータの客観的な分析を提示することを目指していた。",
  "plausible": "The witness provided a plausible account of the events that night. / 証人はその夜の出来事についてもっともらしい説明を提供した。",
  "prevalent": "Burnout is increasingly prevalent among healthcare professionals. / 燃え尽き症候群は医療従事者の間でますます広まっている。",
  "rational": "A rational approach to risk management requires careful analysis. / リスク管理への合理的なアプローチは慎重な分析を必要とする。",
  "sustainable": "The company has committed to adopting sustainable business practices. / 会社は持続可能なビジネス慣行を採用することを約束した。",
  "systematic": "A systematic review of existing literature was conducted first. / まず既存の文献の体系的なレビューが実施された。",
  "transparent": "The hiring process must be fully transparent to ensure fairness. / 採用プロセスは公平性を確保するために完全に透明でなければならない。",
  "viable": "Solar energy is now a commercially viable alternative to fossil fuels. / 太陽エネルギーは今や化石燃料に代わる商業的に実行可能な代替手段だ。",
  "valid": "The results were statistically valid and reproducible across multiple studies. / その結果は統計的に有効で複数の研究にわたって再現可能であった。",
  "substantial": "The program delivered substantial improvements in student performance. / そのプログラムは生徒の成績に実質的な改善をもたらした。",
  "strategic": "The acquisition was a strategic move to expand into emerging markets. / その買収は新興市場への参入を拡大するための戦略的な動きだった。",
  "significant": "The trial revealed a significant reduction in the rate of relapse. / 試験は再発率の著しい減少を示した。",
  "relevant": "Only information directly relevant to the case was admitted as evidence. / 事件に直接関連する情報のみが証拠として認められた。",
  "predominant": "The predominant cause of air pollution in cities is vehicle emissions. / 都市の大気汚染の主要な原因は自動車の排気ガスだ。",
  "autonomous": "The vehicle operates in a fully autonomous mode without human input. / その車両は人間の操作なしに完全自律モードで動作する。",
  "adequate": "The available resources were barely adequate to complete the project. / 利用可能なリソースはプロジェクトを完了するのにかろうじて十分だった。",
  "compatible": "The new software is fully compatible with existing operating systems. / 新しいソフトウェアは既存のオペレーティングシステムと完全に互換性がある。",
  "concurrent": "The trial ran concurrent with an independent investigation into the matter. / 裁判はその件に関する独立した調査と並行して行われた。",
  "marginal": "The improvements were so marginal as to be almost imperceptible. / 改善はほとんど気づかないほどわずかだった。",
  "proportional": "The punishment should be proportional to the severity of the offense. / 罰は犯罪の重大さに比例すべきだ。",
  "accordingly": "The situation changed, and plans were adjusted accordingly. / 状況が変化し、計画はそれに応じて調整された。",
  "adequately": "The health system was not adequately prepared for a pandemic of this scale. / 保健システムはこの規模のパンデミックに十分に備えていなかった。",
  "consequently": "The project was underfunded and consequently fell well behind schedule. / プロジェクトは資金不足であり、その結果大幅に遅延した。",
  "effectively": "The measure effectively reduced crime rates in the targeted areas. / その措置は対象地域での犯罪率を効果的に削減した。",
  "essentially": "The two proposals are essentially identical in their core objectives. / 二つの提案はその中心目標において本質的に同一だ。",
  "inevitably": "Such rapid industrialization inevitably leads to environmental degradation. / そのような急速な工業化は必然的に環境悪化をもたらす。",
  "progressively": "The patient's condition worsened progressively over several weeks. / 患者の状態は数週間にわたって徐々に悪化した。",
  "subsequently": "The report was published and subsequently translated into twelve languages. / 報告書は発表され、続いて12の言語に翻訳された。",
  "ultimately": "All efforts to save the factory ultimately proved unsuccessful. / 工場を救うためのすべての努力は最終的に失敗に終わった。",
  "explicitly": "The guidelines explicitly prohibit the use of confidential information. / ガイドラインは機密情報の使用を明示的に禁止している。",
  "abdicate": "The king abdicated the throne in favor of his eldest son. / 王は長男に有利になるよう王位を退いた。",
  "abolish": "Campaigners have long sought to abolish the death penalty entirely. / 運動家たちは長い間、死刑を完全に廃止しようとしてきた。",
  "abstain": "Several delegates chose to abstain rather than vote against the resolution. / いくつかの代表団は決議に反対票を投じるよりも棄権することを選んだ。",
  "ameliorate": "Targeted interventions can ameliorate the worst effects of urban poverty. / 的を絞った介入は都市貧困の最悪の影響を改善できる。",
  "appease": "The government attempted to appease protesters with minor policy adjustments. / 政府は軽微な政策調整で抗議者をなだめようとした。",
  "arbitrate": "An independent body was established to arbitrate disputes between parties. / 当事者間の紛争を仲裁するために独立機関が設立された。",
  "ascribe": "Critics ascribe the project's failure to a lack of strategic planning. / 批評家はプロジェクトの失敗を戦略的計画の欠如に帰する。",
  "capitulate": "After months of sanctions, the regime finally capitulated to international pressure. / 数ヶ月の制裁の後、政権はついに国際的圧力に降伏した。",
  "coerce": "The suspect claimed he was coerced into signing the false confession. / 容疑者は虚偽の自白に署名するよう強制されたと主張した。",
  "consolidate": "The merger was designed to consolidate market share and reduce competition. / 合併は市場シェアを強化し競争を減らすように設計されていた。",
  "contend": "Several nations contend for influence over the strategically vital region. / いくつかの国が戦略的に重要な地域の影響力をめぐって争っている。",
  "corroborate": "The witness's testimony corroborated the documentary evidence presented. / 証人の証言は提示された文書証拠を裏付けた。",
  "culminate": "Years of tension culminated in a full-scale diplomatic breakdown. / 長年の緊張は全面的な外交的崩壊に最高点に達した。",
  "debilitate": "Chronic stress can debilitate the immune system over time. / 慢性的なストレスは時間をかけて免疫系を衰弱させる可能性がある。",
  "delineate": "The report carefully delineates the boundaries of each administrative zone. / 報告書は各行政区域の境界を慎重に描写している。",
  "depreciate": "The value of the currency has depreciated sharply against the dollar. / 通貨の価値はドルに対して急激に下落した。",
  "disseminate": "The organization works to disseminate accurate health information globally. / その組織は正確な健康情報を世界に普及させるために活動している。",
  "emancipate": "The movement sought to emancipate workers from exploitative labor conditions. / その運動は労働者を搾取的な労働条件から解放しようとした。",
  "encapsulate": "This poem encapsulates the profound sorrow of an entire generation. / この詩は一世代全体の深い悲しみを凝縮している。",
  "enumerate": "The document enumerates the rights and responsibilities of all citizens. / その文書はすべての市民の権利と責任を列挙している。",
  "epitomize": "Her career epitomizes the challenges faced by women in leadership roles. / 彼女のキャリアはリーダー職における女性が直面する課題の典型を示している。",
  "exacerbate": "Austerity measures only served to exacerbate the economic crisis further. / 緊縮財政措置は経済危機をさらに悪化させるだけだった。",
  "expedite": "The committee voted to expedite the approval process for essential medicines. / 委員会は必須医薬品の承認プロセスを迅速化することを決議した。",
  "extrapolate": "It is dangerous to extrapolate sweeping conclusions from limited data sets. / 限られたデータセットから大きな結論を外挿するのは危険だ。",
  "fabricate": "The accused was found to have fabricated key evidence in the trial. / 被告は裁判で重要な証拠を捏造したことが判明した。",
  "fluctuate": "Global oil prices fluctuate in response to geopolitical developments. / 世界の石油価格は地政学的な動向に応じて変動する。",
  "foster": "The program fosters critical thinking and independent research skills. / そのプログラムは批判的思考と独立した研究スキルを育てる。",
  "hamper": "Red tape continues to hamper the efficient delivery of foreign aid. / 官僚的手続きが外国援助の効率的な提供を妨げ続けている。",
  "impede": "Poor infrastructure seriously impedes economic development in the region. / 劣悪なインフラは地域の経済発展を深刻に妨げている。",
  "infer": "From his tone, she inferred that he was deeply disappointed. / 彼の口調から、彼女は彼が非常に失望していると推測した。",
  "mitigate": "Urban green spaces help to mitigate the worst effects of heat islands. / 都市の緑地はヒートアイランドの最悪の影響を緩和するのに役立つ。",
  "mobilize": "The charity mobilized volunteers from across the country to help survivors. / チャリティーは生存者を助けるために全国からボランティアを動員した。",
  "nullify": "The court ruled to nullify the contract on grounds of misrepresentation. / 裁判所は不実表示を理由に契約を無効にすることを判決した。",
  "obliterate": "The bombing campaign obliterated the city's historic infrastructure. / 爆撃作戦は街の歴史的なインフラを消滅させた。",
  "perpetuate": "Systemic inequality perpetuates cycles of poverty across generations. / 構造的な不平等は世代を超えた貧困の連鎖を永続させる。",
  "postulate": "The theory postulates that language shapes our perception of reality. / その理論は言語が現実の認識を形成するということを仮定している。",
  "precipitate": "The abrupt resignation of the minister precipitated a government crisis. / 大臣の突然の辞任は政府危機を引き起こした。",
  "procure": "The agency was tasked with procuring medical supplies for the affected region. / その機関は被災地のために医療用品を調達する任務を与えられた。",
  "propagate": "Social media algorithms can inadvertently propagate false information. / SNSのアルゴリズムは意図せず虚偽の情報を広める可能性がある。",
  "ratify": "All member states must ratify the treaty before it enters into force. / すべての加盟国は条約が発効する前に批准しなければならない。",
  "reconcile": "It proved difficult to reconcile conflicting testimony from witnesses. / 証人からの相反する証言を調整することは困難であることが判明した。",
  "scrutinize": "Auditors scrutinized the company's financial records for discrepancies. / 監査人は食い違いを求めて会社の財務記録を精査した。",
  "supersede": "The updated guidelines supersede all previous versions and instructions. / 更新されたガイドラインはすべての以前のバージョンと指示に取って代わる。",
  "transcend": "Great art has the capacity to transcend cultural and linguistic boundaries. / 偉大な芸術は文化的・言語的境界を超える力を持っている。",
  "underpin": "Strong institutional frameworks underpin stable and prosperous societies. / 強固な制度的枠組みが安定した繁栄する社会を支えている。",
  "vindicate": "The acquittal served to vindicate him after years of false accusations. / 無罪判決は長年の虚偽の非難の後で彼の正当性を証明した。",
  "wane": "Support for the controversial policy began to wane after the scandal broke. / スキャンダルが明らかになった後、物議を醸す政策への支持は衰え始めた。",
  "exonerate": "New DNA evidence was used to exonerate the wrongfully convicted man. / 新たなDNA証拠が不当に有罪判決を受けた男性を免除するために使われた。",
  "abrogate": "The new government moved swiftly to abrogate the previous administration's treaties. / 新政府は前政権の条約を廃止するために素早く動いた。",
  "circumscribe": "His authority was tightly circumscribed by the board of directors. / 彼の権限は取締役会によって厳しく制限されていた。",
  "confiscate": "Customs officials confiscated the undeclared goods at the border. / 税関職員は国境で未申告の商品を没収した。",
  "contravene": "The company's practices were found to contravene environmental law. / 会社の慣行は環境法に違反していることが判明した。",
  "demarcate": "A fence was erected to demarcate the boundary between the two properties. / 二つの所有地の境界を定めるためにフェンスが設置された。",
  "disparage": "It is unprofessional to disparage colleagues in a public forum. / 公開の場で同僚を軽蔑するのはプロらしくない。",
  "divulge": "The journalist refused to divulge the identity of the confidential source. / ジャーナリストは秘密の情報源の身元を明かすことを拒否した。",
  "elucidate": "The professor elucidated the complex theory with several vivid examples. / 教授はいくつかの生き生きとした例を使って複雑な理論を解明した。",
  "impugn": "The defense attorney attempted to impugn the credibility of the witness. / 弁護人は証人の信頼性に異議を唱えようとした。",
  "preclude": "His prior convictions precluded him from holding public office. / 彼の以前の有罪判決は彼が公職に就くことを妨げた。",
  "allude": "The speaker alluded to unresolved tensions without naming any party directly. / 講演者はいかなる当事者も直接名指しせずに未解決の緊張を暗示した。",
  "insinuate": "She insinuated that the results had been manipulated without proof. / 彼女は証拠なしに結果が操作されたとほのめかした。",
  "cavil": "He tends to cavil at minor details rather than address the main issue. / 彼は主要な問題に対処するよりも細かい点に言いがかりをつける傾向がある。",
  "cogitate": "The philosopher cogitated for years before publishing his seminal work. / 哲学者は重要な著作を発表する前に何年もかけて深く考えた。",
  "condone": "Society must not condone any form of discrimination or prejudice. / 社会はいかなる形の差別や偏見も大目に見てはならない。",
  "denigrate": "The media's tendency to denigrate politicians undermines public trust. / 政治家を貶める傾向があるメディアは公的信頼を損なう。",
  "equivocate": "The minister equivocated when pressed for a clear commitment on taxes. / 大臣は税金について明確なコミットメントを求められた際に言葉を濁した。",
  "obfuscate": "Technical jargon is sometimes used to obfuscate rather than clarify. / 専門用語は時に明確にするよりも難解にするために使われる。",
  "palliate": "The medication serves only to palliate symptoms rather than cure the disease. / その薬は病気を治すのではなく症状を緩和するだけだ。",
  "prevaricate": "When questioned directly, the official began to prevaricate. / 直接質問されると、その官僚はごまかし始めた。",
  "promulgate": "The new regulations were officially promulgated and took immediate effect. / 新しい規制が正式に公布され、即時に発効した。",
  "remonstrate": "The workers remonstrated with management over the unsafe conditions. / 労働者たちは危険な状況について経営陣に抗議した。",
  "repudiate": "The candidate publicly repudiated the extremist views attributed to him. / 候補者は自分に帰せられた過激な見解を公に否定した。",
  "ruminate": "She ruminated on the implications of her decision for several sleepless nights. / 彼女は自分の決断の影響について何夜も眠れぬ夜に熟考した。",
  "sequester": "The jury was sequestered to prevent exposure to media coverage. / 陪審員はメディア報道にさらされないよう隔離された。",
  "vacillate": "His tendency to vacillate on key issues undermined his leadership. / 重要な問題について優柔不断になる彼の傾向がリーダーシップを損なった。",
  "waive": "The defendants chose to waive their right to a jury trial. / 被告たちは陪審裁判を受ける権利を放棄することを選んだ。",
  "accentuate": "The new lighting was used to accentuate the architectural features of the facade. / 新しい照明は建物の外観の建築的特徴を際立たせるために使われた。",
  "admonish": "The judge admonished the defendant to remain silent during proceedings. / 裁判官は被告に手続き中は沈黙を保つよう戒めた。",
  "aggravate": "Ignoring the early warning signs only aggravated the situation further. / 早期警告サインを無視することは状況をさらに悪化させただけだった。",
  "beguile": "The con artist beguiled victims with an elaborate tale of fictitious wealth. / 詐欺師は架空の富についての巧みな話で被害者を欺いた。",
  "castigate": "The editorial castigated the government's failure to act on housing reform. / 社説は住宅改革に行動しない政府の失敗を厳しく批判した。",
  "decipher": "Linguists worked for decades to decipher the ancient script. / 言語学者は古代の文字を解読するために数十年かけて研究した。",
  "galvanize": "The shocking footage galvanized the public into demanding immediate action. / 衝撃的な映像は国民を即時行動を求めるよう活気づけた。",
  "inculcate": "Schools have a responsibility to inculcate values of tolerance and respect. / 学校は寛容と尊重の価値を教え込む責任を持っている。",
  "mollify": "The company tried to mollify customers by offering full refunds. / 会社は全額返金を提供することで顧客をなだめようとした。",
  "placate": "Concessions were offered to placate the increasingly frustrated workforce. / ますます不満を募らせる労働者をなだめるために譲歩が提示された。",
  "aberration": "This outbreak was regarded as a statistical aberration rather than a trend. / この発生は傾向ではなく統計的な逸脱と見なされた。",
  "abstraction": "The discussion moved from practical concerns into the realm of abstraction. / 議論は実際の懸念から抽象的な領域へと移っていった。",
  "adversity": "Her remarkable career was shaped by overcoming significant personal adversity. / 彼女の注目すべきキャリアは重大な個人的逆境を克服することによって形成された。",
  "allegory": "The novel functions as an allegory for the dangers of unchecked power. / その小説は抑制されない権力の危険性の寓話として機能している。",
  "ambivalence": "His ambivalence about the promotion was evident to his closest colleagues. / 昇進についての彼の相反する感情は最も親しい同僚には明らかだった。",
  "anachronism": "Using quill pens in the modern office is a charming but obvious anachronism. / 現代のオフィスで羽根ペンを使うことは愛らしいが明らかな時代錯誤だ。",
  "antithesis": "His reckless spending was the antithesis of the prudence the job demanded. / 彼の無謀な支出は仕事が求める思慮深さの対極にあった。",
  "apprehension": "There was growing apprehension about the long-term consequences of the policy. / 政策の長期的な影響への不安が高まっていた。",
  "arbitration": "Both sides agreed to resolve the dispute through binding arbitration. / 双方は拘束力のある仲裁を通じて紛争を解決することに同意した。",
  "archetype": "The stern mentor is a recurring archetype in classical heroic narratives. / 厳格な師は古典的な英雄的物語の中で繰り返し現れる原型だ。",
  "attrition": "The prolonged conflict became a war of attrition with enormous casualties. / 長引く紛争は甚大な死傷者をもたらす消耗戦となった。",
  "brevity": "The brevity of the speech was widely praised by an impatient audience. / 演説の簡潔さは焦れた聴衆から広く称賛された。",
  "bureaucracy": "Excessive bureaucracy delays critical decisions and stifles innovation. / 過剰な官僚主義は重要な決定を遅らせ革新を抑制する。",
  "chicanery": "The trial exposed years of financial chicanery by senior executives. / 裁判は上級幹部による長年の財務的詐欺的行為を暴露した。",
  "cognition": "Advances in neuroscience have transformed our understanding of human cognition. / 神経科学の進歩は人間の認知に対する私たちの理解を変革した。",
  "connotation": "The term carries strong negative connotations in certain cultural contexts. / その用語は特定の文化的文脈では強い否定的な含意を持っている。",
  "contingency": "The government prepared contingency plans for a range of possible emergencies. / 政府はさまざまな緊急事態に備えて不測の事態への計画を準備した。",
  "credibility": "The minister's credibility was severely damaged by the leaked documents. / 漏洩した文書によって大臣の信頼性は深刻に損なわれた。",
  "culmination": "The ceremony was the culmination of five years of extraordinary effort. / その式典は5年間の並外れた努力の絶頂だった。",
  "deference": "In deference to local customs, the delegates modified their formal attire. / 地元の慣習への敬意から、代表団はフォーマルな服装を変更した。",
  "deliberation": "After considerable deliberation, the board approved the new strategy. / かなりの熟考の後、取締役会は新戦略を承認した。",
  "dichotomy": "The strict dichotomy between theory and practice is often misleading. / 理論と実践の厳格な二分法はしばしば誤解を招く。",
  "dilemma": "The organization faces a dilemma between profitability and social responsibility. / 組織は収益性と社会的責任の間のジレンマに直面している。",
  "dissonance": "There was a jarring dissonance between his words and his actions. / 彼の言葉と行動の間には耳障りな不協和があった。",
  "eloquence": "The senator's eloquence moved many in the chamber to reconsider their position. / 上院議員の雄弁は議会の多くの人々に立場を再考させた。",
  "empiricism": "Modern science rests on the philosophical foundation of empiricism. / 現代科学は経験主義の哲学的基盤の上に成り立っている。",
  "enigma": "The origin of the ancient monument remains an enigma to archaeologists. / その古代遺跡の起源は考古学者たちにとってなお謎のままだ。",
  "euphemism": "The term 'collateral damage' is a widely criticized military euphemism. / 「副次的被害」という用語は広く批判されている軍事的婉曲表現だ。",
  "fallacy": "The argument contains a fundamental fallacy that undermines its entire logic. / その議論にはその論理全体を損なう根本的な誤謬が含まれている。",
  "fortitude": "She bore her prolonged illness with remarkable fortitude and grace. / 彼女は長引く病気を驚くべき不屈の精神と優雅さで耐えた。",
  "hegemony": "The decline of Western hegemony has reshaped the global political order. / 西洋の覇権の衰退は世界的な政治秩序を再構成した。",
  "hubris": "The CEO's hubris ultimately led to the downfall of the entire corporation. / CEOの傲慢さは最終的に企業全体の没落をもたらした。",
  "ideology": "The party's ideology has shifted considerably toward the political center. / 党のイデオロギーは政治的中道へと大きくシフトした。",
  "impasse": "Negotiations reached an impasse as neither party would make concessions. / どちらの当事者も譲歩しようとせず交渉は行き詰まりに達した。",
  "incongruity": "The incongruity between his humble origins and lavish lifestyle was striking. / 彼の謙虚な生い立ちと豪華なライフスタイルの不調和は際立っていた。",
  "indifference": "Public indifference to the issue is the greatest obstacle to reform. / その問題への社会的無関心が改革の最大の障害だ。",
  "juxtaposition": "The juxtaposition of wealth and poverty in the city is deeply unsettling. / 都市における富と貧困の並置は深く不安を覚えさせる。",
  "lethargy": "The lethargy of the administration frustrated reformers throughout the country. / 行政の無気力は全国の改革者たちをいらいらさせた。",
  "magnitude": "Few fully appreciate the magnitude of the challenge facing the next generation. / 次の世代が直面する課題の大きさを十分に理解している人は少ない。",
  "malice": "The judge concluded that the defendant acted with deliberate malice. / 裁判官は被告が意図的な悪意をもって行動したと結論付けた。",
  "manifesto": "The new party published its manifesto ahead of the general election. / 新党は総選挙に先立ち宣言書を発表した。",
  "metamorphosis": "The city underwent a remarkable metamorphosis after decades of neglect. / 数十年の放置の後、都市は目覚ましい変容を遂げた。",
  "metaphor": "The author employs the metaphor of a journey to represent personal growth. / 著者は個人の成長を表すために旅の隠喩を用いている。",
  "nihilism": "His bleak worldview bordered on nihilism, denying any inherent meaning in life. / 彼の暗い世界観は人生に固有の意味を否定する虚無主義に近かった。",
  "nuance": "Effective diplomacy requires a keen appreciation of linguistic nuance. / 効果的な外交は言語的ニュアンスへの鋭い理解を必要とする。",
  "oligarchy": "The country has gradually descended into what critics call a corporate oligarchy. / その国は批評家たちが企業寡頭制と呼ぶものへとゆっくりと転落した。",
  "omnipotence": "The philosopher questioned whether true omnipotence is a coherent concept. / 哲学者は真の全能が一貫した概念かどうかを疑問視した。",
  "paradigm": "The discovery triggered a fundamental shift in the prevailing scientific paradigm. / その発見は支配的な科学的パラダイムにおける根本的な転換を引き起こした。",
  "periphery": "Rural communities on the periphery of the economy are often underserved. / 経済の周辺にある農村コミュニティはしばしば十分なサービスを受けていない。",
  "pragmatism": "The negotiations succeeded largely because of both sides' pragmatism. / 交渉が成功したのは主として双方の実用主義によるものだった。",
  "pretense": "He maintained a pretense of calm while internally struggling with doubt. / 彼は内心で疑念と格闘しながら冷静さという見せかけを保った。",
  "propaganda": "State propaganda distorted the historical record for political purposes. / 国家プロパガンダは政治的目的のために歴史的記録を歪めた。",
  "reciprocity": "Diplomacy functions on the principle of reciprocity between nations. / 外交は国家間の相互性の原則の上で機能する。",
  "redundancy": "The report was criticized for its tedious redundancy and lack of originality. / 報告書は退屈な冗長性と独創性の欠如で批判された。",
  "rhetoric": "Her political rhetoric was eloquent but ultimately hollow in substance. / 彼女の政治的修辞は雄弁だったが最終的に中身が空だった。",
  "skepticism": "There is widespread skepticism about whether the targets can be met. / 目標が達成できるかどうかについて広範な懐疑主義がある。",
  "sovereignty": "The dispute raises fundamental questions about national sovereignty. / その紛争は国家主権についての根本的な疑問を提起する。",
  "stigma": "Mental illness still carries a significant stigma in many parts of the world. / 精神疾患は世界の多くの地域でいまだに重大な汚名を帯びている。",
  "stratagem": "The general devised an elaborate stratagem to outmaneuver the enemy. / 将軍は敵を出し抜くための精巧な策略を考案した。",
  "synthesis": "The book attempts a grand synthesis of Eastern and Western philosophical traditions. / その本は東西の哲学的伝統の壮大な統合を試みている。",
  "tautology": "The argument was dismissed as a mere tautology with no explanatory value. / その議論は説明的価値のない単なる冗語として却下された。",
  "tyranny": "History is replete with examples of tyranny dressed in the guise of order. / 歴史は秩序という仮面をつけた専制の例に満ちている。",
  "utopia": "The vision of a fully equal society remains a utopia for many thinkers. / 完全に平等な社会のビジョンは多くの思想家にとってユートピアのままだ。",
  "veracity": "The veracity of his account was eventually confirmed by independent sources. / 彼の説明の誠実さは最終的に独立した情報源によって確認された。",
  "vicissitude": "The company survived the vicissitudes of the global market with resilience. / 会社は世界市場の変遷を回復力をもって乗り越えた。",
  "acrimony": "The negotiations ended in acrimony, with both sides exchanging bitter accusations. / 交渉は双方が激しい非難を交わしながら辛辣さの中で終わった。",
  "alacrity": "She accepted the challenging assignment with remarkable alacrity. / 彼女は挑戦的な任務を驚くべき敏速さで受け入れた。",
  "animosity": "Long-standing animosity between the two factions complicated peace efforts. / 二派間の根深い敵意が和平努力を複雑にした。",
  "cacophony": "The trading floor was a cacophony of shouting voices and ringing phones. / 取引フロアは怒鳴り声と電話の鳴り響く不協和音だった。",
  "complacency": "The organization's complacency allowed serious problems to go undetected. / 組織の自己満足は深刻な問題が見逃される原因となった。",
  "compunction": "She felt no compunction about reporting her colleague's unethical behavior. / 彼女は同僚の非倫理的な行動を報告することに良心の呵責を感じなかった。",
  "consternation": "The surprise announcement was met with consternation across the industry. / 突然の発表は業界全体に狼狽をもって迎えられた。",
  "credulity": "The con man exploited the credulity of elderly victims to steal their savings. / 詐欺師は高齢の被害者の信じやすさを利用して貯蓄を盗んだ。",
  "cupidity": "His cupidity drove him to accept bribes that ultimately destroyed his career. / 彼の強欲は最終的にキャリアを破壊した賄賂を受け入れさせた。",
  "diffidence": "Her natural diffidence made it difficult for her to assert herself in meetings. / 彼女の生来の自信のなさは会議で自己主張することを難しくした。",
  "duplicity": "The diplomat's duplicity was eventually exposed through intercepted communications. / 外交官の二枚舌は傍受された通信によって最終的に暴露された。",
  "equanimity": "She faced the devastating diagnosis with admirable equanimity and resolve. / 彼女は壊滅的な診断を称賛すべき平静と決意をもって受け止めた。",
  "felicity": "The felicity of rural life was reflected in his serene and unhurried prose. / 農村生活の幸福は彼の穏やかで急がない散文に反映されていた。",
  "fervor": "The volunteers worked with extraordinary fervor to support the relief effort. / ボランティアたちは救援活動を支援するために並外れた情熱で働いた。",
  "gravitas": "The veteran diplomat brought considerable gravitas to the sensitive negotiations. / ベテラン外交官はデリケートな交渉にかなりの重厚さをもたらした。",
  "impunity": "The corrupt officials acted with impunity, knowing they would face no consequences. / 腐敗した役人たちは結果を恐れずに免罰で行動した。",
  "iniquity": "The report documented the widespread iniquity of the colonial system. / 報告書は植民地制度の広範な不正を記録した。",
  "mendacity": "The witness's mendacity was eventually exposed during cross-examination. / 証人の虚偽性は尋問中に最終的に暴露された。",
  "oblivion": "Once celebrated, the poet fell into oblivion after his controversial later works. / かつて称賛されたその詩人は物議を醸した後期の作品の後に忘却に落ちた。",
  "parsimony": "His parsimony extended even to refusing adequate heating in the office. / 彼の倹約はオフィスでの十分な暖房を拒否することにまで及んだ。",
  "predilection": "The curator had a well-known predilection for avant-garde contemporary art. / キュレーターは前衛的な現代アートへの周知された好みを持っていた。",
  "proclivity": "His proclivity for risk-taking eventually led to a catastrophic business failure. / リスクを取る彼の傾向は最終的に壊滅的なビジネスの失敗につながった。",
  "propensity": "There is a well-documented propensity for humans to overestimate their abilities. / 人間が自分の能力を過大評価する傾向が十分に記録されている。",
  "protagonist": "The protagonist of the novel struggles with the moral ambiguity of modern life. / 小説の主人公は現代生活の道徳的曖昧さと格闘している。",
  "vindication": "The court's ruling was seen as a complete vindication of her position. / 裁判所の判決は彼女の立場の完全な正当化として見られた。",
  "sycophancy": "The leader surrounded himself with sycophancy rather than honest advisors. / リーダーは誠実な顧問ではなく媚びへつらいで自分を囲んだ。",
  "turpitude": "He was dismissed from office on grounds of moral turpitude and dishonesty. / 彼は道徳的堕落と不誠実を理由に職を解かれた。",
  "umbrage": "The diplomat took considerable umbrage at the perceived slight. / 外交官は認識された軽蔑にかなりの不快感を覚えた。",
  "venality": "The venality of the regime was exposed by a series of corruption scandals. / 政権の賄賂体質は一連の汚職スキャンダルによって暴露された。",
  "verisimilitude": "The novel's historical verisimilitude is enhanced by meticulous period detail. / 小説の歴史的な真実らしさは細心の時代の細部によって高められている。",
  "vituperation": "The debate descended into personal vituperation rather than substantive argument. / 討論は実質的な議論ではなく個人的な罵倒へと堕していった。",
  "xenophobia": "Rising xenophobia has undermined social cohesion in several European countries. / 高まる外国人嫌いはいくつかのヨーロッパ諸国で社会的結束を損なっている。",
  "zealotry": "Religious zealotry has historically been used to justify extreme acts of violence. / 宗教的熱狂主義は歴史的に極端な暴力行為を正当化するために使われてきた。",
  "zenith": "The empire reached its zenith during the reign of its most celebrated emperor. / 帝国は最も著名な皇帝の治世中に頂点に達した。",
  "prologue": "The prologue sets out the philosophical framework for the entire novel. / 序文は小説全体の哲学的枠組みを提示している。",
  "abomination": "The destruction of the ancient temples was regarded as an abomination. / 古代神殿の破壊は嫌悪の対象として見なされた。",
  "cachet": "Graduating from that institution carries considerable cachet in the industry. / その機関を卒業することは業界においてかなりの名声を持っている。",
  "debacle": "The launch was a complete debacle that cost the company millions. / 発売は会社に何百万もの損失をもたらした完全な大失敗だった。",
  "epitome": "Her career is often cited as the epitome of resilience and determination. / 彼女のキャリアは回復力と決意の典型としてしばしば引用される。",
  "fiasco": "The event turned into a fiasco when the main speakers failed to appear. / 主要な登壇者が現れなかったとき、そのイベントは大失敗になった。",
  "foible": "His tendency to arrive late was a minor foible that colleagues learned to accept. / 遅刻する彼の傾向は同僚たちが受け入れることを学んだ小さな欠点だった。",
  "incumbency": "The advantages of incumbency give sitting politicians a significant electoral edge. / 在職の利点は現職の政治家に大きな選挙上の優位性を与える。",
  "lacuna": "Critics identified a significant lacuna in the theory's treatment of causation. / 批評家たちは因果関係の扱いにおける理論の重大な欠落を特定した。",
  "maelstrom": "The city was swept up in the political maelstrom following the election. / 都市は選挙後の政治的大混乱に飲み込まれた。",
  "ennui": "Prolonged isolation gave rise to a deep sense of ennui among the residents. / 長引く孤立は住民たちの間に深い倦怠感を生み出した。",
  "aberrant": "The aberrant behavior of a few individuals should not define the entire group. / 少数の個人の異常な行動がグループ全体を定義すべきではない。",
  "ambivalent": "Many voters remain deeply ambivalent about the proposed constitutional changes. / 多くの有権者は提案された憲法改正について深く相反する感情を持っている。",
  "anachronistic": "Maintaining such anachronistic policies in a modern economy is counterproductive. / 現代経済においてそのような時代錯誤の政策を維持することは逆効果だ。",
  "arcane": "The legal proceedings were filled with arcane terminology that confused the jury. / 法的手続きは陪審員を混乱させる難解な専門用語で満ちていた。",
  "arduous": "The ascent to the summit proved more arduous than the team had anticipated. / 頂上への登山はチームが予想していたよりも困難であることが判明した。",
  "astute": "The astute investor recognized the market opportunity before others did. / 抜け目のない投資家は他の人々よりも先に市場機会を認識した。",
  "austere": "The monastery's austere interior reflected the monks' commitment to simplicity. / 修道院の厳格な内装は修道士たちの質素さへのコミットメントを反映していた。",
  "benevolent": "The benevolent donor funded scholarships for hundreds of underprivileged students. / 慈悲深い寄付者は何百人もの恵まれない学生への奨学金に資金を提供した。",
  "candid": "The CEO gave a remarkably candid assessment of the company's difficulties. / CEOは会社の困難について驚くほど率直な評価を行った。",
  "capricious": "The minister's capricious decisions made coherent planning almost impossible. / 大臣の気まぐれな決定は一貫した計画をほぼ不可能にした。",
  "circumspect": "Diplomats must be highly circumspect in their choice of public statements. / 外交官は公的声明の選択において非常に慎重でなければならない。",
  "cogent": "The report presents a cogent case for fundamental reform of the tax system. / 報告書は税制の根本的な改革への説得力のある主張を提示している。",
  "contentious": "The proposed legislation proved highly contentious among opposition lawmakers. / 提案された法律は野党議員の間で非常に争いを引き起こすことが判明した。",
  "convoluted": "The regulatory process was so convoluted that businesses struggled to comply. / 規制プロセスは非常に複雑に絡み合っていたため、企業はコンプライアンスに苦労した。",
  "cynical": "Years of political disappointment had made him deeply cynical about democracy. / 長年の政治的失望が彼を民主主義について深く皮肉的にしていた。",
  "daunting": "The scale of the reconstruction effort was truly daunting. / 復興努力の規模は本当に気をくじくものだった。",
  "dogmatic": "A dogmatic adherence to outdated theories impedes genuine scientific progress. / 時代遅れの理論への独断的な固執は真の科学的進歩を妨げる。",
  "eloquent": "Her eloquent speech moved the entire audience to tears. / 彼女の雄弁な演説は聴衆全体を涙させた。",
  "enigmatic": "The artist's enigmatic smile has fascinated viewers for centuries. / その芸術家の謎めいた微笑みは何世紀もの間鑑賞者を魅了してきた。",
  "ephemeral": "Fame in the digital age can be as ephemeral as a trending social media post. / デジタル時代の名声はトレンドのSNS投稿と同じくらいはかない。",
  "equivocal": "The committee's equivocal response failed to reassure investors. / 委員会の曖昧な返答は投資家を安心させることに失敗した。",
  "erroneous": "The report was based on erroneous assumptions about market behavior. / 報告書は市場の行動についての誤った仮定に基づいていた。",
  "exorbitant": "The exorbitant cost of housing has driven many residents out of the city. / 法外な住居コストが多くの住民を都市から追い出した。",
  "fallacious": "The argument is fundamentally fallacious and rests on false premises. / その議論は根本的に誤っており虚偽の前提に基づいている。",
  "formidable": "The new competitor posed a formidable challenge to established market leaders. / 新しい競合他社は確立された市場リーダーに強大な挑戦を突きつけた。",
  "gratuitous": "The film was criticized for its gratuitous violence and lack of narrative purpose. / その映画は不必要な暴力と物語的目的の欠如で批判された。",
  "immutable": "The laws of physics appear immutable regardless of time or location. / 物理法則は時間や場所に関わらず不変のように見える。",
  "imperious": "Her imperious manner alienated colleagues who might otherwise have supported her. / 彼女の横柄な態度は他の状況では彼女を支持したかもしれない同僚を疎外した。",
  "incessant": "The incessant noise from the construction site disrupted residents for months. / 建設現場からの絶え間ない騒音が何ヶ月もの間住民を悩ませた。",
  "incongruous": "His cheerful demeanor seemed incongruous given the gravity of the occasion. / 場の重大さを考えると彼の陽気な態度は不調和に見えた。",
  "indignant": "She was deeply indignant at being passed over for the promotion. / 彼女は昇進を見送られたことに深く憤慨した。",
  "insidious": "The insidious effects of misinformation can take years to undo. / 誤情報の陰険な影響を取り消すには何年もかかる可能性がある。",
  "intrepid": "The intrepid journalist risked her safety to report from the conflict zone. / 大胆なジャーナリストは紛争地帯から報道するために安全を危険にさらした。",
  "judicious": "A judicious allocation of resources is essential for any long-term strategy. / リソースの賢明な配分はあらゆる長期戦略に不可欠だ。",
  "ludicrous": "The claim that the policy would solve poverty overnight was ludicrous. / 政策が一夜にして貧困を解決するという主張はばかげていた。",
  "magnanimous": "The victor was magnanimous in defeat and extended an olive branch to rivals. / 勝者は敗北において寛大で、ライバルたちに和解の手を差し伸べた。",
  "mendacious": "The mendacious testimony seriously undermined the prosecution's case. / 虚偽の証言は検察の事件を深刻に損なった。",
  "meticulous": "The forensic team conducted a meticulous examination of the crime scene. / 鑑識チームは犯罪現場の細心の審査を実施した。",
  "nefarious": "The investigation uncovered the nefarious activities of a criminal syndicate. / 調査は犯罪組織の極悪な活動を明らかにした。",
  "obsequious": "His obsequious behavior toward his superiors was transparent and embarrassing. / 上司への彼のこびへつらう行動は見え透いていて恥ずかしかった。",
  "ostentatious": "The ostentatious display of wealth was widely regarded as a provocation. / 富の見せびらかしは広く挑発として見なされた。",
  "pedantic": "His pedantic insistence on minor grammatical errors irritated his colleagues. / 細かい文法的誤りへの彼の衒学的な固執は同僚たちをいらいらさせた。",
  "perfidious": "The alliance collapsed after one partner's perfidious betrayal. / 一方のパートナーの不誠実な裏切りの後、同盟は崩壊した。",
  "precocious": "The precocious child read advanced texts that were intended for adults. / その早熟な子供は大人向けの高度なテキストを読んでいた。",
  "taciturn": "The taciturn scientist rarely spoke at conferences unless directly addressed. / 無口な科学者は直接声をかけられない限りカンファレンスではほとんど話さなかった。",
  "tenacious": "The tenacious campaigner refused to abandon the cause despite repeated defeats. / 粘り強い運動家は繰り返しの敗北にもかかわらず活動を諦めることを拒否した。",
  "ubiquitous": "Smartphones have become so ubiquitous that life without them seems unimaginable. / スマートフォンはどこにでもあるものとなり、それなしの生活は想像できない。",
  "voracious": "Her voracious appetite for knowledge drove her to read dozens of books a year. / 知識への彼女の貪欲な欲求は彼女を年間数十冊の本を読むよう駆り立てた。",
  "acrimonious": "The divorce proceedings became increasingly acrimonious over property disputes. / 離婚手続きは財産紛争をめぐってますます辛辣になった。",
  "bellicose": "The nation's bellicose rhetoric alarmed its neighbors and international observers. / その国の好戦的な修辞は近隣諸国と国際的な観察者を警戒させた。",
  "bombastic": "His bombastic speech impressed no one who was familiar with the actual facts. / 彼の大げさな演説は実際の事実を知っている誰も感銘を与えなかった。",
  "disingenuous": "It seemed disingenuous to claim ignorance of the firm's unethical practices. / 会社の非倫理的な慣行を知らないと主張するのは不誠実に見えた。",
  "evanescent": "The peace agreement proved evanescent, collapsing within weeks of being signed. / 和平合意は署名されてから数週間以内に崩壊し、消えやすいことが証明された。",
  "garrulous": "The garrulous witness provided far more detail than the court required. / おしゃべりな証人は法廷が必要とするよりはるかに多くの詳細を提供した。",
  "impetuous": "His impetuous decision to resign surprised both friends and adversaries alike. / 辞任するという彼の衝動的な決断は友人も敵対者も同様に驚かせた。",
  "incorrigible": "Despite repeated warnings, the incorrigible violator continued to break the rules. / 繰り返しの警告にもかかわらず、矯正不可能な違反者は規則を破り続けた。",
  "inveterate": "He was an inveterate traveler who had visited over a hundred countries. / 彼は百カ国以上を訪問した根深い旅行者だった。",
  "loquacious": "The loquacious professor often strayed from his lecture topic into tangential anecdotes. / 多弁な教授はしばしば講義のトピックから脇道にそれた逸話へと迷い込んだ。",
  "obdurate": "The obdurate landowner refused every offer to sell, despite financial pressure. / 頑固な地主は財政的プレッシャーにもかかわらず、あらゆる売却の申し出を断った。",
  "perfunctory": "His perfunctory apology satisfied no one affected by his actions. / 彼のおざなりの謝罪は彼の行動に影響された誰も満足させなかった。",
  "abstruse": "The abstruse mathematical proof took years for other specialists to verify. / 難解な数学的証明は他の専門家が検証するのに何年もかかった。",
  "acerbic": "Her acerbic wit made her reviews entertaining but feared by the artists. / 彼女の辛辣な機知は批評を面白くしたが、芸術家たちには恐れられた。",
  "aloof": "The new director maintained an aloof manner that few colleagues could warm to. / 新しいディレクターは、ほとんどの同僚が親しみを感じられないよそよそしい態度を保った。",
  "altruistic": "Her altruistic commitment to charitable work defined her entire public life. / 慈善活動への彼女の利他的なコミットメントは彼女の全ての公的生活を定義した。",
  "banal": "The speech was dismissed as a series of banal platitudes with no substance. / 演説は中身のない陳腐な決まり文句の連続として却下された。",
  "callous": "The company's callous disregard for worker safety prompted a public outcry. / 労働者の安全への会社の冷淡な無視が公の抗議を引き起こした。",
  "clandestine": "The agents conducted a clandestine operation without the knowledge of their allies. / エージェントたちは同盟国の知識なしに秘密の作戦を遂行した。",
  "dilatory": "The committee adopted dilatory tactics to prevent the bill from coming to a vote. / 委員会は法案が採決されるのを防ぐために引き延ばし戦術を採用した。",
  "fastidious": "The chef was fastidious in his preparation, rejecting any ingredient below standard. / シェフは準備において口うるさく、基準以下のいかなる食材も拒否した。",
  "furtive": "A furtive glance at his phone revealed he was not paying attention. / 彼の携帯電話へのこそこそした一瞥は彼が注意を払っていないことを明らかにした。",
  "hapless": "The hapless traveler missed his connection and lost his luggage on the same day. / 不運な旅行者は同じ日に乗り換えに乗り遅れ、荷物も失った。",
  "inane": "The meeting was wasted on inane small talk rather than substantive discussion. / 会議は実質的な議論ではなく無意味な雑談に費やされた。",
  "innocuous": "What appeared to be an innocuous comment sparked a significant controversy. / 無害に見えたコメントが重大な論争を引き起こした。",
  "insipid": "Critics described the film as insipid and devoid of any original ideas. / 批評家たちはその映画を味気なく独創的なアイデアが全くないと描写した。",
  "intransigent": "Both sides remained intransigent, refusing to concede on core demands. / 双方は中心的な要求について譲歩することを拒否し妥協しないままだった。",
  "arbitrarily": "Resources were arbitrarily allocated without any clear guiding criteria. / リソースは明確な指針となる基準なしに恣意的に配分された。",
  "categorically": "The spokesperson categorically denied any knowledge of the alleged conspiracy. / 報道官は主張された陰謀についていかなる知識も断固として否定した。",
  "conspicuously": "Her absence from the ceremony was conspicuously noted by all attendees. / 式典からの彼女の欠席はすべての出席者によって目立って注目された。",
  "emphatically": "The prime minister emphatically rejected any suggestion of economic mismanagement. / 首相は経済失政のいかなる示唆も強調して拒絶した。",
  "inexorably": "The glacier is inexorably retreating due to rising global temperatures. / 氷河は上昇する地球温度により容赦なく後退している。",
  "intrinsically": "The problem is intrinsically complex and cannot be reduced to simple solutions. / その問題は本質的に複雑であり、単純な解決策に還元することはできない。",
  "paradoxically": "Paradoxically, stricter environmental laws sometimes stimulate industrial innovation. / 逆説的に、より厳しい環境法が時に産業的革新を刺激することがある。",
  "succinctly": "The brief summary succinctly captured the essence of the lengthy report. / 短い要約は長い報告書の本質を簡潔に捉えていた。",
  "unequivocally": "The evidence unequivocally demonstrated the defendant's innocence. / 証拠は被告の無実を明確に示していた。",
  "vociferously": "Protesters vociferously demanded the immediate release of political prisoners. / 抗議者たちは政治囚の即時釈放を声高に要求した。",
};
